import { PaletteType } from "../types";

const Palettes: PaletteType[] = [
    // {
    //     background: "#DDDDCC",
    //     accent: "#922f54",
    // accentDark: "#4858A9",
    //     stripLinesColor: "#fbfbfb",
    //     name: "Dahlia",
    //     colorsA: [
    //         { color: "#d0c66d", opacity: 1 },
    //         { color: "#d24b64", opacity: 1 },
    //         { color: "#574D62", opacity: 1 },
    //         { color: "#4badc3", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#E58263", opacity: 1 },
    //         { color: "#C32E51", opacity: 1 },
    //         { color: "#524576", opacity: 1 },
    //         { color: "#2A6D93", opacity: 1 },
    //     ],
    //     colorsC: [
    //         { color: "#D7481B", opacity: 1 },
    //         { color: "#8e1f48", opacity: 1 },
    //         { color: "#3c2c68", opacity: 1 },
    //         { color: "#284a71", opacity: 1 },
    //     ],
    //     colorsD: [
    //         { color: "#2B968F", opacity: 1 },
    //         { color: "#27698E", opacity: 1 },
    //         { color: "#851C3C", opacity: 1 },
    //         { color: "#8C81A4", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#E4E4DD",
    //     accent: "#255A8B",
    // accentDark: "#4858A9",
    //     name: "Cerulean",
    //     stripLinesColor: "#fcfcfd",
    //     colorsA: [
    //         { color: "#91CED6", opacity: 1 },
    //         { color: "#9CBDB5", opacity: 1 },
    //         { color: "#A1D1B4", opacity: 1 },
    //         { color: "#E6837C", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#46A2C0", opacity: 1 },
    //         { color: "#72CFCF", opacity: 1 },
    //         { color: "#58C0A7", opacity: 1 },
    //         { color: "#FF6978", opacity: 1 },
    //     ],
    //     colorsC: [
    //         { color: "#295A88", opacity: 1 },
    //         { color: "#3097C2", opacity: 1 },
    //         { color: "#2C968F", opacity: 1 },
    //         { color: "#9F1B3A", opacity: 1 },
    //     ],
    //     colorsD: [
    //         { color: "#EEAF66", opacity: 1 },
    //         { color: "#C67344", opacity: 1 },
    //         { color: "#BDA299", opacity: 1 },
    //         { color: "#DB6262", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#E1C233",
    //     accent: "#BC722D",
    // accentDark: "#4858A9",
    //     name: "Retro",
    //     stripLinesColor: "#fefdfc",
    //     colorsA: [
    //         { color: "#FF8C4B", opacity: 1 },
    //         { color: "#DF404A", opacity: 1 },
    //         { color: "#2897C2", opacity: 1 },
    //         { color: "#7C9886", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#CE473E", opacity: 1 },
    //         { color: "#9B223F", opacity: 1 },
    //         { color: "#0C4F73", opacity: 1 },
    //         { color: "#5D6C7A", opacity: 1 },
    //     ],
    //     colorsC: [
    //         { color: "#E7932F", opacity: 1 },
    //         { color: "#E25643", opacity: 1 },
    //         { color: "#60A16E", opacity: 1 },
    //         { color: "#96A347", opacity: 1 },
    //     ],
    //     colorsD: [
    //         { color: "#E2992C", opacity: 1 },
    //         { color: "#B1442C", opacity: 1 },
    //         { color: "#475847", opacity: 1 },
    //         { color: "#5C9599", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#dee1ed",
    //     accent: "#4858A9",
    //     accentDark: "#9ca3c4",
    //     pencilColor: "#59639b",
    //     name: "Coral",
    //     stripLinesColor: "#f9f9fb",
    //     trianglesColor: "#c6cce1",
    //     colorsA: [
    //         { color: "#FF698C", opacity: 1 },
    //         { color: "#BD7CF1", opacity: 1 },
    //         { color: "#555BEA", opacity: 1 },
    //         { color: "#B8D2E4", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#E94F6A", opacity: 1 },
    //         { color: "#F195B2", opacity: 1 },
    //         { color: "#E8E8E8", opacity: 1 },
    //         { color: "#B3A2DD", opacity: 1 },
    //         { color: "#50C5DE", opacity: 1 },
    //     ],
    //     colorsC: [
    //         { color: "#B3A2DD", opacity: 1 },
    //         { color: "#643ED0", opacity: 1 },
    //         { color: "#84589F", opacity: 1 },
    //         { color: "#5478AD", opacity: 1 },
    //     ],
    //     colorsD: [
    //         { color: "#a6b1c4", opacity: 1 },
    //         { color: "#B8D2E4", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#011627",
    //     accent: "#4C657A",
    //     name: "Hanabi",
    //     colorsA: [
    //         { color: "#D62828", opacity: 1 },
    //         { color: "#F77F00", opacity: 1 },
    //         { color: "#E2F1AF", opacity: 1 },
    //         { color: "#F6F7F8", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#680025", opacity: 1 },
    //         { color: "#8B0800", opacity: 1 },
    //         { color: "#6F8148", opacity: 1 },
    //         { color: "#947369", opacity: 1 },
    //     ],
    // },
    // // {
    // //     background: "#C5283D",
    // //     accent: "#FAE0E0",
    // //     colorsA: [
    // //         { color: "#E28413", opacity: 1 },
    // //         { color: "#E4C94C", opacity: 1 },
    // //         { color: "#E4FDE1", opacity: 1 },
    // //         { color: "#BBA0CA", opacity: 1 },
    // //         { color: "#865AB6", opacity: 1 },
    // //     ],
    // //     colorsB: [
    // //         { color: "#891833", opacity: 1 },
    // //         { color: "#D7481B", opacity: 1 },
    // //         { color: "#5273A5", opacity: 1 },
    // //         { color: "#4E46A3", opacity: 1 },
    // //         { color: "#39316D", opacity: 1 },
    // //     ],
    // // },
    // // {
    // //     background: "#107f69",
    // //     accent: "#102928",
    // //     colorsA: [
    // //         { color: "#E94F6A", opacity: 1 },
    // //         { color: "#F195B2", opacity: 1 },
    // //         { color: "#E8E8E8", opacity: 1 },
    // //         { color: "#B3A2DD", opacity: 1 },
    // //         { color: "#50C5DE", opacity: 1 },
    // //     ],
    // //     colorsB: [
    // //         { color: "#6D1043", opacity: 1 },
    // //         { color: "#A63270", opacity: 1 },
    // //         { color: "#634D81", opacity: 1 },
    // //         { color: "#4650A3", opacity: 1 },
    // //         { color: "#084E75", opacity: 1 },
    // //     ],
    // // },
    // {
    //     background: "#262122",
    //     accent: "#5F5149",
    //     name: "Saffron",
    //     colorsA: [
    //         { color: "#8C0837", opacity: 1 },
    //         { color: "#D62828", opacity: 1 },
    //         { color: "#F05555", opacity: 1 },
    //         { color: "#FAA526", opacity: 1 },
    //         { color: "#FAE526", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#43091E", opacity: 1 },
    //         { color: "#6A0606", opacity: 1 },
    //         { color: "#A62525", opacity: 1 },
    //         { color: "#933214", opacity: 1 },
    //         { color: "#D45A14", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#53917E",
    //     accent: "#D2C8A4",
    //     name: "Academia",
    //     colorsA: [
    //         { color: "#DC4762", opacity: 1 },
    //         { color: "#FF8E4F", opacity: 1 },
    //         { color: "#FCD0A1", opacity: 1 },
    //         { color: "#C9C7C0", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#992648", opacity: 1 },
    //         { color: "#A32918", opacity: 1 },
    //         { color: "#9C5140", opacity: 1 },
    //         { color: "#6D5C4C", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#2C2A4A",
    //     accent: "#84589F",
    //     name: "Nightlife",
    //     colorsA: [
    //         { color: "#7FDEFF", opacity: 1 },
    //         { color: "#E4FDE1", opacity: 1 },
    //         { color: "#FFF174", opacity: 1 },
    //         { color: "#FFBFCE", opacity: 1 },
    //         { color: "#DABFFF", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#2486E1", opacity: 1 },
    //         { color: "#52A5A5", opacity: 1 },
    //         { color: "#D78C1B", opacity: 1 },
    //         { color: "#BC408B", opacity: 1 },
    //         { color: "#68509B", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#EAE3D1",
    //     accent: "#AC8F8F",
    //     name: "Linen",
    //     colorsA: [
    //         { color: "#97B381", opacity: 1 },
    //         { color: "#E1E897", opacity: 1 },
    //         { color: "#F5A65B", opacity: 1 },
    //         { color: "#BE5E68", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#596F2A", opacity: 1 },
    //         { color: "#94A143", opacity: 1 },
    //         { color: "#CB511D", opacity: 1 },
    //         { color: "#5C0E26", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#E4DED5",
    //     accent: "#B64830",
    //     name: "Dawnbreak",
    //     colorsA: [
    //         { color: "#E28413", opacity: 1 },
    //         { color: "#F4D04F", opacity: 1 },
    //         { color: "#BDD1BB", opacity: 1 },
    //         { color: "#5AABB6", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#78211C", opacity: 1 },
    //         { color: "#BF4721", opacity: 1 },
    //         { color: "#11666B", opacity: 1 },
    //         { color: "#14426C", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#7D463A",
    //     accent: "#DF8856",
    //     name: "Cinnamon",
    //     colorsA: [
    //         { color: "#76C88F", opacity: 1 },
    //         { color: "#FCF6B1", opacity: 1 },
    //         { color: "#F7B32B", opacity: 1 },
    //         { color: "#F72C25", opacity: 1 },
    //         { color: "#9B56A4", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#315A46", opacity: 1 },
    //         { color: "#A17540", opacity: 1 },
    //         { color: "#A1430C", opacity: 1 },
    //         { color: "#7D221C", opacity: 1 },
    //         { color: "#41284D", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#DDD4D0",
    //     accent: "#A04A73",
    //     name: "Sundown",
    //     colorsA: [
    //         { color: "#F9C22E", opacity: 1 },
    //         { color: "#F15946", opacity: 1 },
    //         { color: "#7A5980", opacity: 1 },
    //         { color: "#444465", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#B3571F", opacity: 1 },
    //         { color: "#8F0B3B", opacity: 1 },
    //         { color: "#381956", opacity: 1 },
    //         { color: "#081535", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#EBEBEB",
    //     accent: "#6CA2B4",
    //     name: "Verdant",
    //     colorsA: [
    //         { color: "#5C687F", opacity: 1 },
    //         { color: "#10AFB9", opacity: 1 },
    //         { color: "#2CDA9D", opacity: 1 },
    //         { color: "#F9DF74", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#1E3157", opacity: 1 },
    //         { color: "#114968", opacity: 1 },
    //         { color: "#0F708E", opacity: 1 },
    //         { color: "#B7951C", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#22201E",
    //     accent: "#A49A3F",
    //     name: "Topsoil",
    //     colorsA: [
    //         { color: "#9F5B34", opacity: 1 },
    //         { color: "#EEE84D", opacity: 1 },
    //         { color: "#D3EE87", opacity: 1 },
    //         { color: "#09814A", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#51313B", opacity: 1 },
    //         { color: "#D8883F", opacity: 1 },
    //         { color: "#60723C", opacity: 1 },
    //         { color: "#24322B", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#EEF5DB",
    //     accent: "#B9B29F",
    //     name: "Mediterranean",
    //     colorsA: [
    //         { color: "#6CCFF6", opacity: 1 },
    //         { color: "#FFC857", opacity: 1 },
    //         { color: "#ED6A5E", opacity: 1 },
    //         { color: "#C17767", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#2078A9", opacity: 1 },
    //         { color: "#C77B23", opacity: 1 },
    //         { color: "#962424", opacity: 1 },
    //         { color: "#7E3B3B", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#EFF6EE",
    //     accent: "#FF7575",
    //     name: "Springtime",
    //     colorsA: [
    //         { color: "#ED5E5E", opacity: 1 },
    //         { color: "#F4D04F", opacity: 1 },
    //         { color: "#A5E059", opacity: 1 },
    //         { color: "#36A99E", opacity: 1 },
    //         { color: "#3F52EE", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#962424", opacity: 1 },
    //         { color: "#AF7A12", opacity: 1 },
    //         { color: "#4E8C31", opacity: 1 },
    //         { color: "#1F5D61", opacity: 1 },
    //         { color: "#1D2656", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#6d7755",
    //     accent: "#4D4743",
    //     name: "September",
    //     colorsA: [
    //         { color: "#8F9FA9", opacity: 1 },
    //         { color: "#4D4244", opacity: 1 },
    //         { color: "#C84630", opacity: 1 },
    //         { color: "#FF5714", opacity: 1 },
    //         { color: "#F18805", opacity: 1 },
    //         { color: "#CBAD5F", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#3E4A62", opacity: 1 },
    //         { color: "#2C2123", opacity: 1 },
    //         { color: "#85220C", opacity: 1 },
    //         { color: "#8D2A1C", opacity: 1 },
    //         { color: "#944112", opacity: 1 },
    //         { color: "#A85F1C", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#EBECEF",
    //     accent: "#575D97",
    //     name: "Synthetic",
    //     colorsA: [
    //         { color: "#00BBF9", opacity: 1 },
    //         { color: "#00F5D4", opacity: 1 },
    //         { color: "#FEE440", opacity: 1 },
    //         { color: "#F15BB5", opacity: 1 },
    //         { color: "#9B5DE5", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#0A569C", opacity: 1 },
    //         { color: "#0E96B3", opacity: 1 },
    //         { color: "#C9A218", opacity: 1 },
    //         { color: "#B81F56", opacity: 1 },
    //         { color: "#2D318A", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#DDD195",
    //     accent: "#AE4933",
    //     name: "Earthly",
    //     colorsA: [
    //         { color: "#EB552D", opacity: 1 },
    //         { color: "#E4AB59", opacity: 1 },
    //         { color: "#F7DF4C", opacity: 1 },
    //         { color: "#1D8779", opacity: 1 },
    //         { color: "#8971B9", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#84081E", opacity: 1 },
    //         { color: "#B75039", opacity: 1 },
    //         { color: "#B67529", opacity: 1 },
    //         { color: "#11324A", opacity: 1 },
    //         { color: "#272952", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#DEE0E7",
    //     accent: "#3087C7",
    //     name: "Lavender",
    //     colorsA: [
    //         { color: "#9C88EC", opacity: 1 },
    //         { color: "#BD93D8", opacity: 1 },
    //         { color: "#CACCE9", opacity: 1 },
    //         { color: "#7BCDBA", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#2C2F7E", opacity: 1 },
    //         { color: "#5F3595", opacity: 1 },
    //         { color: "#504EA8", opacity: 1 },
    //         { color: "#10689A", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#DDD4D0",
    //     accent: "#66687E",
    //     name: "Prismatic",
    //     colorsA: [
    //         { color: "#F9DF74", opacity: 1 },
    //         { color: "#F9C22E", opacity: 1 },
    //         { color: "#F15946", opacity: 1 },
    //         { color: "#955B9F", opacity: 1 },
    //         { color: "#6456B7", opacity: 1 },
    //         { color: "#319AD6", opacity: 1 },
    //         { color: "#12B8C3", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#B7951C", opacity: 1 },
    //         { color: "#B3571F", opacity: 1 },
    //         { color: "#8F0B3B", opacity: 1 },
    //         { color: "#381956", opacity: 1 },
    //         { color: "#081535", opacity: 1 },
    //         { color: "#0D1D47", opacity: 1 },
    //         { color: "#114968", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#25252D",
    //     accent: "#66687E",
    //     name: "Preem",
    //     colorsA: [
    //         { color: "#ED6A5E", opacity: 1 },
    //         { color: "#FFAC47", opacity: 1 },
    //         { color: "#F4D04F", opacity: 1 },
    //         { color: "#7BCDBA", opacity: 1 },
    //         { color: "#12B8C3", opacity: 1 },
    //         { color: "#55557E", opacity: 1 },
    //         { color: "#945891", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#962424", opacity: 1 },
    //         { color: "#78211C", opacity: 1 },
    //         { color: "#BF4721", opacity: 1 },
    //         { color: "#11666B", opacity: 1 },
    //         { color: "#114968", opacity: 1 },
    //         { color: "#372C4F", opacity: 1 },
    //         { color: "#402E52", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#DDD4D0",
    //     accent: "#8C717E",
    //     name: "Embers",
    //     colorsA: [
    //         { color: "#FFCE4F", opacity: 1 },
    //         { color: "#DD2244", opacity: 1 },
    //         { color: "#3D2F4A", opacity: 1 },
    //         { color: "#16ABDA", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#F2FF5C", opacity: 1 },
    //         { color: "#FF2222", opacity: 1 },
    //         { color: "#49F4FF", opacity: 1 },
    //     ],
    // },
    // {
    //     background: "#171519",
    //     accent: "#D56340",
    //     name: "Jazz",
    //     colorsA: [
    //         // { color: "#F18805", opacity: 1 },
    //         { color: "#FF6542", opacity: 1 },
    //         { color: "#AF9583", opacity: 1 },
    //         // { color: "#779FA1", opacity: 1 },
    //         { color: "#5DB7DE", opacity: 1 },
    //     ],
    //     colorsB: [
    //         { color: "#8C2109", opacity: 1 },
    //         { color: "#743C30", opacity: 1 },
    //         { color: "#F9F5CD", opacity: 1 },
    //         { color: "#3A6172", opacity: 1 },
    //         { color: "#196E93", opacity: 1 },
    //     ],
    // },
];

export default Palettes;
